### ISSUE TITLE
Command line option to enable/disable the plugin

### ISSUE THREAD

**Issue by n-studio** [paleite/eslint-plugin-diff#24]
On my CI I want to lint only the diff lines, but when I run lint locally I want to be able to scan my whole project.

Is it possible to add a command line option, for example `eslint src/** --disable-diff` to restore the default behaviour?

**Comment by paleite** [comment]
That's a great idea! I'll look into it in the next few days.

**Comment by paleite** [comment]
@n-studio I've release a pre-release of this feature. It's pre-released as version `2.0.2-0` and if you like, you could try it out right now. It's completely automatic, so you don't have to specify if you're running in CI or not.

Please note: There's no new command-line option (ESLint doesn't allow that), but since I added auto-detection instead, it should work by simply changing your config from `"plugin:diff/diff"` to `"plugin:diff/ci"`.
